### ISSUE TITLE
Shouldn't it be cursor.fetchall()?

### ISSUE THREAD

**Issue by metehus** [analu-gomes/python_espm#1]
According to the [documentation](https://docs.python.org/3/library/sqlite3.html?highlight=fetchall#sqlite3.Cursor.fetchall), Cursor.fetchall is a function, so I think the following line should be ```result = cursor.fetchall()```

https://github.com/analu-gomes/python_espm/blob/cbdf37f2cfb288d2a45f400dee1ed269ca4068f1/student-n-studentid.py#L86

**Comment by analu-gomes** [comment]
thanks, metehus! it was one of the problems
